hyperparameters:
  batch_size: 32
  # Adam Optimizer
  learning_rate: 0.00025
  b1: 0.9
  b2: 0.999
  gp_lambda: 10
  alpha: 50.0
  n_critic: 5
  max_epochs: 1

# mlflow server --backend-store-uri sqlite:///climatexdb.sqlite --default-artifact-root /home/sbeale/climate_ml_artifacts --port 8080
tracking:
  tracking_uri: sqlite:////home/sbeale/climate_ml_artifacts/climatexdb.sqlite
  default_artifact_root: /home/sbeale/climate_ml_artifacts
  experiment_name: "Ocean-Waves"
  run_name: "CNN"
  description: "Initial setup with 3060 and pytorch lightning. Same config as Annau2023."
  log_every_n_steps: 100

training:
  num_workers: 16
  precision: "32"
  accelerator: "gpu"

data:
  lr_shape:
    - 2 # n_covariates
    - 64 # x size
    - 64 # y size 
  hr_shape:
    - 1 # n_predictands
    - 128 # x size
    - 128 # y size
  files:
    lr_test:
      - /home/sbeale/95_14_glob_w_hawaii_hs/test/uas/lr/*.pt
      - /home/sbeale/95_14_glob_w_hawaii_hs/test/vas/lr/*.pt
    lr_train:
      - /home/sbeale/95_14_glob_w_hawaii_hs/train/uas/lr/*.pt
      - /home/sbeale/95_14_glob_w_hawaii_hs/train/vas/lr/*.pt
    lr_validation:
      - /home/sbeale/95_14_glob_w_hawaii_hs/validation/uas/lr/*.pt
      - /home/sbeale/95_14_glob_w_hawaii_hs/validation/vas/lr/*.pt
    hr_test:
      - /home/sbeale/95_14_glob_w_hawaii_hs/test/hs/hr/*.pt
    hr_train:
      - /home/sbeale/95_14_glob_w_hawaii_hs/train/hs/hr/*.pt
    hr_validation:
      - /home/sbeale/95_14_glob_w_hawaii_hs/validation/hs/hr/*.pt