hyperparameters:
  batch_size: 8
  # Adam Optimizer
  learning_rate: 0.00025
  b1: 0.9
  b2: 0.999
  gp_lambda: 10
  alpha: 50.0
  n_critic: 5
  max_epochs: 4

# mlflow server --backend-store-uri sqlite:///climatexdb.sqlite --default-artifact-root /Users/susanbeale/desktop/climate_ml_artifacts --port 8000
tracking:
  tracking_uri: sqlite:////Users/susanbeale/desktop/climate_ml_artifacts/climatexdb.sqlite
  default_artifact_root: /Users/susanbeale/desktop/climate_ml_artifacts
  experiment_name: "Ocean Waves"
  run_name: "CNN"
  description: "Initial setup with 3060 and pytorch lightning. Same config as Annau2023."
  log_every_n_steps: 100

training:
  num_workers: 8
  precision: "32"
  accelerator: "cpu"

data:
  lr_shape:
    - 2 # n_covariates
    - 16 # x size
    - 16 # y size
  hr_shape:
    - 1 # n_predictands
    - 128 # x size
    - 128 # y size
  files:
    lr_test:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/test/uas/lr/*.pt
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/test/vas/lr/*.pt
    lr_train:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/train/uas/lr/*.pt
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/train/vas/lr/*.pt
    lr_validation:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/validation/uas/lr/*.pt
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/validation/vas/lr/*.pt
    hr_test:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/test/hs/hr/*.pt
    hr_train:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/train/hs/hr/*.pt
    hr_validation:
      - /Users/susanbeale/Desktop/95_97_med_w_small_hs/validation/hs/hr/*.pt
